---
title: "About"
---

```{r}
here::i_am("about.qmd")
```


## About these pages

These pages contain links and resources for our one-off training sessions. You can also find links to our main multi-session training courses via [our TURAS page](https://learn.nes.nhs.scot/36791). All our sessions are:

-   live and practical/interactive. They aren't scripted, and they prioritise Q&A, working through the material, and collective problem-solving
-   free to attend
-   open to all
-   aimed at members of the KIND workforce across Scotland's health, social care, and housing sector

## About the KIND learning network

The KIND learning network is an inclusive and supportive community of practice for staff across the knowledge, information, and data workforce. It exists to further the leading role of the community in the digital transformation of health and care by supporting learning, sharing of best practice, and developing interdisciplinary collaborations.

## What does KIND stand for?

KIND = **K**nowledge, **I**nformation, and **D**ata.

These topics roughly correspond to three main professional groups:

-   those who work with data and/or information
-   those working in knowledge management, research & development, and libraries
-   those working in records

## Who is the KIND network for?

The KIND network is open to everyone, but is particularly aimed at staff from Scotland’s health, social care, and housing workforce who are interested in developing their knowledge, information, and data skills.

## What does the KIND network do?

The KIND network does three main things:

1.  We provide a range of training courses aimed at developing specialist professional skills. For example, we run Excel, Power BI, and R training courses at a range of levels. All our courses are free to access.
2.  We provide a social learning space in the Teams channel, with a range of events aimed at different aspects of this area of work. For example, we run a weekly topic-based community meetup session and a mentoring scheme.
3.  We work with key national stakeholders to support and champion these training and learning activities. For example, we are currently developing resources to support analysts transitioning to R.

All these activities are responsive to your needs. If you feel there’s an important area of relevant work where we are not contributing, please get in touch.

## Who runs/owns/funds the KIND network?

The KIND Learning Network is based at NHS Education for Scotland, as part of the Digitally Enabled Workforce programme. That’s a programme that builds foundational resources to support digital skills and leadership at all levels. You might have heard about our Professional Development Award in Technology Enabled Care programme, used the M365 Skills Hub, or been involved with the Digital Leadership Programme. This work is all funded through Scottish Government via the Digital Health and Care Portfolio Board.

## Why does the KIND network exist?

This network exists to support people who work with knowledge, information, and data as they work to transform health and social care. There’s a large (and growing) workforce responsible for this work in Scotland. However, this workforce is really diverse. It’s not like e.g. nursing or other NMHAP professions where there are fixed entry and promotion criteria. Professional development is more complicated and messy than that. A good example is the lack of standardised job titles for KIND workers. We currently have something like 350 different job titles in the Teams channel. That splitting up of job families contributes to KIND workers being less visible than I think they should be. Kathleen Grey and colleagues called them “[ghosts in the machine](https://pubmed.ncbi.nlm.nih.gov/30741187/)”

## Where does KIND work happen?

KIND work happens in many places across health and social care in Scotland. For example, you might find KIND workers in NHS Boards (national or territorial), other governmental health bodies, Local Authorities, social care care organisations, higher education, in the private sector, professional associations, or in health and social care partnerships

## Help! I have an unmet query…

-   [Teams channel link](https://teams.microsoft.com/l/team/19%3AQZ7-PbFVcziG2piHLt1_ifey3I2cwFL0yBuTSS8vVao1%40thread.tacv2/conversations?groupId=106d08f3-9026-40e2-b3c7-87cd87304d58&tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a) = [Mailing list link](https://forms.office.com/pages/responsepage.aspx?id=veDvEDCgykuAnLXmdF5JmpopIZB9ynRJnrPUHVFccipURjM2NkZJUkhGOFlQRjQxRFhVUTgwT0UwVyQlQCN0PWcu)
-   For anything, please contact Brendan Clarke (brendan.clarke2\@nhs.scot).
