---
title: "Power Platform training"
execute: 
  freeze: false
listing:
  contents:
    - "bi_training/*.qmd"
  type: table
  categories: true
  fields: [title, categories]
editor_options: 
  chunk_output_type: console
---

```{r}
library(readr)
library(dplyr)
library(stringr)

source(here::here("R/training_sessions.R"))

```

If you work for NHS Scotland, do please note the [NHSS National M365 guidance](https://scottish.sharepoint.com/sites/NHSSNationalM365ServiceHub/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNHSSNationalM365ServiceHub%2FShared%20Documents%2FTT%20Resources%2FUsing%20Microsoft%20365%20Tools%20appropriately%2Epdf&parent=%2Fsites%2FNHSSNationalM365ServiceHub%2FShared%20Documents%2FTT%20Resources) before implementing any projects using new M365 applications.

```{r}
cat("## Power Platform training schedule")
```

```{r}

KINDR::training_sessions(tr_type = c("Power BI", "Power BI / Excel", "Power Platform"), output_type = "DT", start_date = as.character(lubridate::today() - 1))

```

## Power Platform session materials










