---
title: "KIND training"
---

```{r}
# if renv misfires, force the lockfile to update
# lock <- renv:::lockfile("renv.lock")
# lock$repos(CRAN = "https://cran.rstudio.com")
# lock$write("renv.lock")
```

## The KIND network

We're a supportive and inclusive social learning space for staff working with knowledge, information, and data, across Scotland's health, social care, and housing sector.  \n

These pages contain the materials for the range of one-off training sessions provided by NHS Education for Scotland's KIND learning network.

## How to use these materials

+ all our sessions are designed to be delivered live on Teams
+ all these materials are creative-commons licensed, so please feel free to reuse within those conditions
+ these sessions are periodically re-run, <a href="mailto:brendan.clarke2@nhs.scot">so please get in touch</a> if you'd find it helpful to have one or more sessions re-offered

## Thanks

These materials owe a huge debt to the many members of the KIND community who have contributed. More specifically, these pages are based on [Melissa Van Bussell's video](https://www.youtube.com/watch?v=arzBRW5XIkg) describing, with absolute clarity, how to deploy Quarto websites to GitHub pages.
